
import { VocabItem, GameList } from './types';

export const VOCABULARY: Record<GameList, VocabItem[]> = {
  [GameList.ListA]: [
    { id: 'a1', entry: 'addition', pos: 'n', meaningArabic: 'إضافة/ توسيع', meaningEnglish: 'Adding/extension/inclusion' },
    { id: 'a2', entry: 'advance', pos: 'n', meaningArabic: 'تقدّم/ اكتشافات', meaningEnglish: 'progress' },
    { id: 'a3', entry: 'analysis', pos: 'n', meaningArabic: 'تحليل', meaningEnglish: 'Investigation/search/act of examining' },
    { id: 'a4', entry: 'appear', pos: 'v', meaningArabic: 'يبدو/ يظهر', meaningEnglish: 'Seem / to start to be seen' },
    { id: 'a5', entry: 'approach', pos: 'v, n', meaningArabic: 'يتعامل مع / نهج', meaningEnglish: 'deal with, method' },
    { id: 'a6', entry: 'average', pos: 'adj', meaningArabic: 'معدّل/ عادي', meaningEnglish: 'ordinary, usual' },
    { id: 'a7', entry: 'challenge', pos: 'v', meaningArabic: 'يعترض/ يتحدى', meaningEnglish: 'to compete / express disagreement' },
    { id: 'a8', entry: 'chance', pos: 'n', meaningArabic: 'فرصة/ مخاطرة', meaningEnglish: 'Risk / opportunity' },
    { id: 'a9', entry: 'characteristic', pos: 'n', meaningArabic: 'سمة / صفة مميزة', meaningEnglish: 'a typical or noticeable quality' },
    { id: 'a10', entry: 'consequence', pos: 'n', meaningArabic: 'عاقبة', meaningEnglish: 'as a result' },
    { id: 'a11', entry: 'debate', pos: 'v, n', meaningArabic: 'مناقشة', meaningEnglish: 'serious discussion of a subject' },
    { id: 'a12', entry: 'decrease', pos: 'v, n', meaningArabic: 'ينخفض / انخفاض', meaningEnglish: 'to become less' },
    { id: 'a13', entry: 'definition', pos: 'n', meaningArabic: 'تعريف', meaningEnglish: 'a statement of the exact meaning' },
    { id: 'a14', entry: 'demonstrate', pos: 'v', meaningArabic: 'يظهر / يبرهن', meaningEnglish: 'to show or make something clear' },
    { id: 'a15', entry: 'despite', pos: 'prep', meaningArabic: 'على الرغم من', meaningEnglish: 'without being influenced' },
    { id: 'a16', entry: 'detail', pos: 'n', meaningArabic: 'تفصيل', meaningEnglish: 'a single piece of information' },
    { id: 'a17', entry: 'device', pos: 'n', meaningArabic: 'جهاز', meaningEnglish: 'object that has been invented' },
    { id: 'a18', entry: 'digital', pos: 'adj', meaningArabic: 'رقمي', meaningEnglish: 'using computers or the internet' },
    { id: 'a19', entry: 'direct', pos: 'adj, v', meaningArabic: 'مباشر / يوجه', meaningEnglish: 'without anyone or anything in between' },
    { id: 'a20', entry: 'discovery', pos: 'n', meaningArabic: 'اكتشاف', meaningEnglish: 'the process of finding information' }
  ],
  [GameList.ListB]: [
    { id: 'b1', entry: 'acquire', pos: 'v', meaningArabic: 'يكتسب', meaningEnglish: 'to get or obtain something' },
    { id: 'b2', entry: 'agriculture', pos: 'n', meaningArabic: 'الزراعة', meaningEnglish: 'farming' },
    { id: 'b3', entry: 'anxious', pos: 'adj', meaningArabic: 'قلق / متوتر', meaningEnglish: 'worried and nervous' },
    { id: 'b4', entry: 'atmosphere', pos: 'n', meaningArabic: 'الغلاف الجوي', meaningEnglish: 'the air that you breathe in a place' },
    { id: 'b5', entry: 'calculate', pos: 'v', meaningArabic: 'يحسب', meaningEnglish: 'to determine by mathematical processes' },
    { id: 'b6', entry: 'competitive', pos: 'adj', meaningArabic: 'تنافسي', meaningEnglish: 'wanting very much to win' },
    { id: 'b7', entry: 'continent', pos: 'n', meaningArabic: 'قارة', meaningEnglish: 'one of the seven large land masses' },
    { id: 'b8', entry: 'decade', pos: 'n', meaningArabic: 'عقد', meaningEnglish: 'a period of ten years' },
    { id: 'b9', entry: 'deliver', pos: 'v, n', meaningArabic: 'يوصّل / توصيل', meaningEnglish: 'to take goods, letters, parcels' },
    { id: 'b10', entry: 'detect', pos: 'v', meaningArabic: 'يتحرّى / يستشعر', meaningEnglish: 'to notice something partly hidden' },
    { id: 'b11', entry: 'disaster', pos: 'n', meaningArabic: 'كارثة', meaningEnglish: 'an event that causes great harm' },
    { id: 'b12', entry: 'disease', pos: 'n', meaningArabic: 'مرض', meaningEnglish: 'illness caused by infection' },
    { id: 'b13', entry: 'distance', pos: 'n', meaningArabic: 'مسافة', meaningEnglish: 'the amount of space between places' },
    { id: 'b14', entry: 'double', pos: 'adj, v', meaningArabic: 'مزدوج / يضاعف', meaningEnglish: 'twice as much or as many' },
    { id: 'b15', entry: 'dramatic', pos: 'adj', meaningArabic: 'دراماتيكي / مثير', meaningEnglish: 'sudden, very noticeable' },
    { id: 'b16', entry: 'economical', pos: 'adj', meaningArabic: 'اقتصادي', meaningEnglish: 'not using a lot of money' },
    { id: 'b17', entry: 'efficiency', pos: 'n', meaningArabic: 'كفاءة', meaningEnglish: 'working in a well-organized way' },
    { id: 'b18', entry: 'emphasis', pos: 'n', meaningArabic: 'توكيد / تركيز', meaningEnglish: 'particular importance given to something' },
    { id: 'b19', entry: 'encounter', pos: 'v, n', meaningArabic: 'يواجه / مقابلة', meaningEnglish: 'to experience something unpleasant' },
    { id: 'b20', entry: 'enormous', pos: 'adj', meaningArabic: 'ضخم', meaningEnglish: 'extremely large' }
  ],
  [GameList.ListC]: [
    { id: 'c1', entry: 'absorb', pos: 'v', meaningArabic: 'يمتص', meaningEnglish: 'soak up' },
    { id: 'c2', entry: 'ambition', pos: 'n', meaningArabic: 'طموح', meaningEnglish: 'Desire to achieve a goal' },
    { id: 'c3', entry: 'argue', pos: 'v', meaningArabic: 'يجادل', meaningEnglish: 'persuade, give reasons' },
    { id: 'c4', entry: 'ashamed', pos: 'adj', meaningArabic: 'خجلان/ خجول', meaningEnglish: 'feeling guilty or embarrassed' },
    { id: 'c5', entry: 'barrier', pos: 'n', meaningArabic: 'حاجز / مانع', meaningEnglish: 'something that prevents people' },
    { id: 'c6', entry: 'capture', pos: 'v', meaningArabic: 'يأسر', meaningEnglish: 'to catch someone and make prisoner' },
    { id: 'c7', entry: 'ceremony', pos: 'n', meaningArabic: 'مراسم/ طقوس', meaningEnglish: 'a formal event performed' },
    { id: 'c8', entry: 'courage', pos: 'n', meaningArabic: 'شجاعة', meaningEnglish: 'ability to deal with dangerous situations' },
    { id: 'c9', entry: 'debt', pos: 'n', meaningArabic: 'دَيْن', meaningEnglish: 'money that is owed' },
    { id: 'c10', entry: 'distinguish', pos: 'v', meaningArabic: 'يميز', meaningEnglish: 'to notice the difference' },
    { id: 'c11', entry: 'editor', pos: 'n', meaningArabic: 'محرر', meaningEnglish: 'person in charge of a newspaper' },
    { id: 'c12', entry: 'evidence', pos: 'n', meaningArabic: 'دليل / برهان', meaningEnglish: 'anything that helps to prove' },
    { id: 'c13', entry: 'exhibition', pos: 'n', meaningArabic: 'معرض', meaningEnglish: 'a public show of art or items' },
    { id: 'c14', entry: 'failure', pos: 'n', meaningArabic: 'فشل', meaningEnglish: 'lack of success' },
    { id: 'c15', entry: 'fascinating', pos: 'adj', meaningArabic: 'رائع / فاتن', meaningEnglish: 'extremely interesting' },
    { id: 'c16', entry: 'generate', pos: 'v', meaningArabic: 'يولد / ينتج', meaningEnglish: 'to produce or create' },
    { id: 'c17', entry: 'guarantee', pos: 'v, n', meaningArabic: 'يضمن / ضمان', meaningEnglish: 'a promise that something will happen' },
    { id: 'c18', entry: 'heritage', pos: 'n', meaningArabic: 'تراث', meaningEnglish: 'features belonging to a culture' },
    { id: 'c19', entry: 'identity', pos: 'n', meaningArabic: 'هوية', meaningEnglish: 'who a person is' },
    { id: 'c20', entry: 'impact', pos: 'n', meaningArabic: 'تأثير', meaningEnglish: 'a powerful effect' }
  ],
  [GameList.ListD]: [
    { id: 'd1', entry: 'aggressive', pos: 'adj', meaningArabic: 'عدواني', meaningEnglish: 'hostile, forceful, destructive' },
    { id: 'd2', entry: 'ambassador', pos: 'n', meaningArabic: 'سفير', meaningEnglish: 'an official representative' },
    { id: 'd3', entry: 'bargain', pos: 'n', meaningArabic: 'صفقة/ مساومة', meaningEnglish: 'something on sale at a lower price' },
    { id: 'd4', entry: 'branch', pos: 'n', meaningArabic: 'فرع / غصن', meaningEnglish: 'business or tree part' },
    { id: 'd5', entry: 'bucket', pos: 'n', meaningArabic: 'سطل', meaningEnglish: 'a container with an open top' },
    { id: 'd6', entry: 'cave', pos: 'n', meaningArabic: 'كهف', meaningEnglish: 'a large hole in the side of a hill' },
    { id: 'd7', entry: 'customs', pos: 'n', meaningArabic: 'جمارك', meaningEnglish: 'taxes paid on imported goods' },
    { id: 'd8', entry: 'defeat', pos: 'v, n', meaningArabic: 'يهزم / هزيمة', meaningEnglish: 'to win against someone' },
    { id: 'd9', entry: 'dreadful', pos: 'adj', meaningArabic: 'مروّع', meaningEnglish: 'causing fear, shock, or suffering' },
    { id: 'd10', entry: 'explode', pos: 'v', meaningArabic: 'ينفجر', meaningEnglish: 'to break up into pieces violently' },
    { id: 'd11', entry: 'factor', pos: 'n', meaningArabic: 'عامل', meaningEnglish: 'one of several things that cause result' },
    { id: 'd12', entry: 'global', pos: 'adj', meaningArabic: 'عالمي', meaningEnglish: 'relating to the whole world' },
    { id: 'd13', entry: 'hesitate', pos: 'v', meaningArabic: 'يتردد', meaningEnglish: 'to pause before saying or doing' },
    { id: 'd14', entry: 'indicate', pos: 'v', meaningArabic: 'يشير إلى', meaningEnglish: 'to show, point, or make clear' },
    { id: 'd15', entry: 'justice', pos: 'n', meaningArabic: 'عدالة', meaningEnglish: 'fairness in the way people are treated' },
    { id: 'd16', entry: 'knowledge', pos: 'n', meaningArabic: 'معرفة', meaningEnglish: 'understanding of a subject' },
    { id: 'd17', entry: 'label', pos: 'n, v', meaningArabic: 'ملصق / يصنف', meaningEnglish: 'piece of paper with information' },
    { id: 'd18', entry: 'maintain', pos: 'v', meaningArabic: 'يحافظ على', meaningEnglish: 'to continue to have; keep in existence' },
    { id: 'd19', entry: 'objective', pos: 'n, adj', meaningArabic: 'هدف / موضوعي', meaningEnglish: 'something that you plan to do' },
    { id: 'd20', entry: 'participate', pos: 'v', meaningArabic: 'يشارك', meaningEnglish: 'to take part in an activity' }
  ]
};
